// helpers/pdfHelpers.js
const axios = require('axios');
const FormData = require('form-data');

/**
 * Download a file at the given URL and return it as a Buffer.
 * Used to fetch PDFs generated by external services like QuickChart.
 * @param {string} url
 * @returns {Promise<Buffer>}
 */
async function fetchBufferFromUrl(url) {
  const { data } = await axios.get(url, { responseType: 'arraybuffer' });
  return Buffer.from(data);
}


/**
 * Upload a file buffer to the WhatsApp Cloud API and return the media ID.
 * @param {Buffer} buffer
 * @param {string} filename  e.g. "report.pdf"
 * @param {string} mime      e.g. "application/pdf"
 * @returns {Promise<string>}  media_id
 */
async function uploadToWhatsApp(buffer, filename, mime) {
  const form = new FormData();
  form.append('file', buffer, { filename, contentType: mime });
  form.append('type', mime);
  form.append('messaging_product', 'whatsapp');  // ✅ REQUIRED!

  const { data } = await axios.post(
    `https://graph.facebook.com/v20.0/${process.env.PHONE_NUMBER_ID}/media`,
    form,
    {
      headers: {
        ...form.getHeaders(),
        Authorization: `Bearer ${process.env.WHATSAPP_ACCESS_TOKEN}`,
      },
    },
  );

  return data.id;                     // media_id
}

module.exports = { uploadToWhatsApp, fetchBufferFromUrl };
